---
name: CI checks
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [8, 11, 15, 17]
        jdk: [zulu, adopt]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}_jdk-${{ matrix.jdk }}-${{ matrix.java }}_maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}_jdk-${{ matrix.jdk }}-${{ matrix.java }}_maven-
      - name: Build
        run: mvn -B package
      - name: Verify
        run: mvn -B verify
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}_jdk-adopt-17_maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}_jdk-adopt-17_maven-
      - run: mvn -B checkstyle:check
